---
title: "NBA_DATA_ANALYSIS"
author: "Kecheng Liang"
date: "12/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(benford.analysis)
library(dplyr)
```

```{r}
try <- read.csv("2012-18_playerBoxScore.csv")
```


```{r}


bfd.cp <- benford(try$playAST,number.of.digits = 1)
bfd.cp1 <- benford(try_awayAST$playAST,number.of.digits = 1)

plot(bfd.cp)

bfd.cp

try_awayAST <- filter(try,try$teamLoc=="Away")
try_homeAST <- filter(try,try$teamLoc=="Home")

try$playAST <- as.numeric(try$playAST)

boxplot(x=try_awayAST$playAST)
boxplot(x=try_homeAST$playAST)

hist(x=try_awayAST$playAST)
hist(x=try_homeAST$playAST)

#t.test(try_awayAST$playAST, try_homeAST$playAST, alternative = "two.sided", var.equal = FALSE)

#try$away <- dplyr::filter(try$teamLoc,"Away")

a <- table(try_homeAST$playAST)
b <- table(try_awayAST$playAST)
length(b) <- length(a)
c <- cbind(a,b)
c <- as.data.frame(c)
c[is.na(c)] <- 0
chisq.test(c)

chi <- chisq.test(try_awayAST$playAST, try_homeAST$playAST)

tbl <- data.frame(group=as.factor(try_awayAST$playAST),race=as.factor(try_homeAST$playAST))

chisq<-chisq.test(try_awayAST$playAST)
chisq
chisq$observed
corrplot(chisq$residuals, is.cor = FALSE)
```

